insert: insert_sort.cpp
	g++ -g insert_sort.cpp -o main

select: select_sort.cpp
	g++ -g select_sort.cpp -o main

bubble: bubble_sort.cpp
	g++ -g bubble_sort.cpp -o main

.PHONY:clean

clean:
	-rm *.o main